# Generated by Django 2.2.24 on 2022-01-10 21:30

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
