# Generated by Django 2.2.24 on 2022-01-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_auto_20220111_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
