# Generated by Django 2.2.24 on 2022-01-11 01:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_auto_20220111_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/'),
        ),
    ]
